version: "3"

services:
  db:
    image: mongo:4-bionic
    volumes:
      - mongoData:/data/db
    networks:
      - default

  cms:
    image: akrantz01/cockpit-cms:latest
    build:
      context: ./cms
    environment:
      COCKPIT_EXTERNAL_DATABASE: "true"
      COCKPIT_DATABASE_SERVER: mongodb://db:27017
      COCKPIT_DATABASE_NAME: cockpit
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

volumes:
  mongoData: {}
