version: "3"

services:
  db:
    image: mongo:4-bionic
    volumes:
      - mongoData:/data/db
    networks:
      - default

  cms:
    image: akrantz01/cockpit-cms:latest
    build:
      context: ./cms
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

volumes:
  mongoData: {}
